### PR TITLE
fixes/responsive-from-mail

### PR DESCRIPTION
**Pull request by IdanSchiller**
This change is [Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28)

### CODE REVIEW

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28)* status: all files reviewed, 5 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/Pages/Contact/Contact.jsx, line 41 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_Ue8iDlswJVUqOAxI:-Mj_Ue8iDlswJVUqOAxJ:baizokg) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Contact/Contact.jsx#L41)):*
> ```JavaScript
> 
>   useEffect(() => {
>     if (!_.isNil(window)) {
> ```

put all of this under try/catch
you can do nothing in the catch but I want to avoid crash 
___
*[src/components/Pages/Contact/Contact.jsx, line 47 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_UqsX9_UUG0z0cqdO:-Mj_UqsZENeFNCmNDiOk:b78rp8a) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Contact/Contact.jsx#L47)):*
> ```JavaScript
>         !_.isNil(queryParamFormType) &&
>         1 <= queryParamFormType &&
>         queryParamFormType <= 3
> ```

put the numbers in a constants with informative names
___
*[src/components/Pages/Home/Home.jsx, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_Ts5cDlOgKesTSg8Z:-Mj_Ts5cDlOgKesTSg8_:b-2qhd5j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L16)):*
> ```JavaScript
> import TadmitVideo from "../../TadmitVideo";
> 
> const BREAK_POINTS = { lg: 1024, md: 769, sm: 640 }; // in px, according to tailwind.config.js screens configurations
> ```

why not just use the config data?
___
*[src/components/Pages/Home/Home.jsx, line 61 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_TwQq5aRl1IHADt4c:-Mj_TwQq5aRl1IHADt4d:borhrke) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L61)):*
> ```JavaScript
>   }, []);
> 
>   var carouselSettings = {
> ```

stop copy-paste `var` shit!
___
*[src/components/Pages/Home/Home.jsx, line 66 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_U3N02mIqpaU5xGMO:-Mj_U3N02mIqpaU5xGMP:b8viz4u) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L66)):*
> ```JavaScript
>     speed: 500,
>     slidesToShow:
>       screenWidth < BREAK_POINTS.sm ? 1 : screenWidth < BREAK_POINTS.md ? 2 : 3,
> ```

what is 1 2 3? can you put it under constants and give it informative names?

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28)* status: all files reviewed, 5 unresolved discussions (waiting on @nir2002)

___
*[src/components/Pages/Contact/Contact.jsx, line 41 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_Ue8iDlswJVUqOAxI:-MjcvuIz9vP7Ho_vQrnc:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Contact/Contact.jsx#L41)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

put all of this under try/catch
you can do nothing in the catch but I want to avoid crash 
</blockquote></details>

Done.
___
*[src/components/Pages/Contact/Contact.jsx, line 47 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_UqsX9_UUG0z0cqdO:-Mjcvu_H295uyBOmO_-z:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Contact/Contact.jsx#L47)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

put the numbers in a constants with informative names
</blockquote></details>

Done.
___
*[src/components/Pages/Home/Home.jsx, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_Ts5cDlOgKesTSg8Z:-MjcyUz2Atp2yajghe3q:b1w1s6p) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L16)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why not just use the config data?
</blockquote></details>

I can't see how I can import it from <code>tailwind.config.js</code>
___
*[src/components/Pages/Home/Home.jsx, line 61 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_TwQq5aRl1IHADt4c:-Mjcxmo-1XzBWaS3CSdu:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L61)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

stop copy-paste `var` shit!
</blockquote></details>

Done.
___
*[src/components/Pages/Home/Home.jsx, line 66 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mj_U3N02mIqpaU5xGMO:-MjcydW51_qGt2U-iPL_:bt4n5w5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6a69d270043715ba285bb233cebffa0065e4fc8a/src/components/Pages/Home/Home.jsx#L66)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what is 1 2 3? can you put it under constants and give it informative names?
</blockquote></details>

it is the number of slides to show, and a number is quite informative in my opinion

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28)* status: all files reviewed, 2 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[src/components/Pages/Contact/Contact.jsx, line 10 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-MjjoWLRCdB-nZykkoIn:-MjjoWLRCdB-nZykkoIo:b-mqn942) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c5b1beedc471731671bacf8ba5ccfc89e0a8e147/src/components/Pages/Contact/Contact.jsx#L10)):*
> ```JavaScript
> import SEO from "../../SEO/SEO";
> 
> const FORM_TYPES = { workInGan: 1, getProducts: 2, general: 3 };
> ```

please change this to:

```
const FORM_TYPES = Object.freeze({
WORK_IN_GAN: 1,
GET_PRODUCTS: 2,
GENERAL: 3
})
```

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

___
*[src/components/Pages/Contact/Contact.jsx, line 13 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/28#-Mjk1tSV-OJwLQH54RbH:-Mjk1tSV-OJwLQH54RbI:b-oy0ov1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/25b9fcf6fa46716988afa9f93c9045425aae4162/src/components/Pages/Contact/Contact.jsx#L13)):*
> ```JavaScript
>   WORK_IN_GAN: 1,
>   GET_PRODUCTS: 2,
>   general: 3,
> ```

GENERAL

**Pull request merged**
