### PR TITLE
feature/work-with-us

### PR DESCRIPTION
**Pull request by IdanSchiller**
This change is [Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)

### CODE REVIEW

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)* status: all files reviewed, 2 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/Pages/Home/Home.jsx, line 9 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcLmxb-lp0El1g_VtD:-MdcLmxb-lp0El1g_VtE:b-l4vpc4) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/fba58c119c482d24dbceefe041e56317c8c9a71c/src/components/Pages/Home/Home.jsx#L9)):*
> ```JavaScript
> import SEO from "../../SEO";
> import TeamGrid from "../../TeamGrid";
> import Carousel from "~src/components/Carousel/Carousel";
> ```

no need for two folders of Carousel :)
___
*[src/components/Pages/Products/Products.jsx, line 51 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcMpVa6O30DInmbkCJ:-MdcMpVa6O30DInmbkCK:b-jjzns0) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/fba58c119c482d24dbceefe041e56317c8c9a71c/src/components/Pages/Products/Products.jsx#L51)):*
> ```JavaScript
> 
>   let contactPageRoute = "/"; // home page as default value
>   if (contactPageRouteObject) contactPageRoute = contactPageRouteObject.href;
> ```

use {}

**Review by nir2002 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)* status: all files reviewed, 3 unresolved discussions (waiting on @IdanSchiller)

*[a discussion](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcQEgEE_lneDbkcJj6:-MdcQEgFAywgwFqNR9CY:b-z3tgc0) (no related file):*
1. There is some strange bug in the footer, please check it out
2. The Facebook-button doesn't look good on a tablet, please fix it

---

**Review by nir2002 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)* status: all files reviewed, 3 unresolved discussions (waiting on @IdanSchiller)

*[a discussion](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcQEgEE_lneDbkcJj6:-MdcQcL42hQzSYBPZj5j:b-wwl661) (no related file):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. There is some strange bug in the footer, please check it out
2. The Facebook-button doesn't look good on a tablet, please fix it
</blockquote></details>

Also take a look at the console, there are some disturbing error messages to fix

---

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)* status: all files reviewed, 3 unresolved discussions (waiting on @nir2002)

*[a discussion](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcQEgEE_lneDbkcJj6:-MdkaLsYEASz1bzzYoO2:b-pysd4l) (no related file):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Also take a look at the console, there are some disturbing error messages to fix
</blockquote></details>

1. If you were referring to the "הגן" word being to close to "חדשנות חינוכית", I fixed it.
2. fixed that 
3. console is cleared

---
___
*[src/components/Pages/Home/Home.jsx, line 9 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcLmxb-lp0El1g_VtD:-MdkPC9TDfVJnERDANJV:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/fba58c119c482d24dbceefe041e56317c8c9a71c/src/components/Pages/Home/Home.jsx#L9)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

no need for two folders of Carousel :)
</blockquote></details>

Done.
___
*[src/components/Pages/Products/Products.jsx, line 51 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcMpVa6O30DInmbkCJ:-MdkOqpG81b5VlAc8svb:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/fba58c119c482d24dbceefe041e56317c8c9a71c/src/components/Pages/Products/Products.jsx#L51)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

use {}
</blockquote></details>

Done.

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

*[a discussion](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/17#-MdcQEgEE_lneDbkcJj6:-Mdl1kXDBOOoBhvuQ-9O:be3jnx0) (no related file):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

1. If you were referring to the "הגן" word being to close to "חדשנות חינוכית", I fixed it.
2. fixed that 
3. console is cleared
</blockquote></details>

התכוונתי לזה שיש רווח ענק לבן מתחת לפוטר
קורה בבראנץ' הזה

---

**Pull request merged**
