### PR TITLE
feature/home-img-carousle

### PR DESCRIPTION
**Pull request by IdanSchiller**
This change is [Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16)

### CODE REVIEW

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16)* status: all files reviewed, 15 unresolved discussions (waiting on @IdanSchiller)

___
*[package.json, line 76 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-Mdc7Zpc-WQ3K7qSjZkb:-Mdc7Zpc-WQ3K7qSjZkc:bghgp0b) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/package.json#L76)):*
> ```JSON
>     "postcss": "^8.2.10",
>     "prettier": "^2.2.1",
>     "react-alice-carousel": "^2.5.1",
> ```

you're using two different packages?
___
*[src/components/Carousel/Carousel/index.js, line 1 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEJZ15j3PFeeUrNih:-MdcEJZ15j3PFeeUrNii:b-iuu7bo) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L1)):*
> ```JavaScript
> import React, {  useEffect } from 'react';
> ```

1. Why do you have two nested folders named Carousel ?
2. rename the file to Carousel and use the index.js pattern
___
*[src/components/Carousel/Carousel/index.js, line 10 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEYyj22nbwvP-fZih:-MdcEYyj22nbwvP-fZii:b-hfi22c) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L10)):*
> ```JavaScript
> 
>   useEffect(() => {
>     const interval = setInterval(() => {
> ```

you can refactor it to:
```
const interval = setInterval(moveToNextItem, time)
```
___
*[src/components/Carousel/Carousel/index.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEhDK0w0FD_u8V5y2:-MdcEhDK0w0FD_u8V5y3:b-rjbpf2) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L13)):*
> ```JavaScript
>       moveToNextItem()
>     }, time);
>     return () => clearInterval(interval);
> ```

I don't think `interval` is defined when this function is called, test it.
___
*[src/components/Carousel/Carousel/index.js, line 17 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEsMlAWeCnhTUx6kr:-MdcEsMlAWeCnhTUx6ks:b-vz4mkm) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L17)):*
> ```JavaScript
> 
>   useEffect(()=>{
>     if(time<1000) time=1000
> ```

1. why?
2. use clause {}
3. save 1000 is informative constant
___
*[src/components/Carousel/Carousel/index.js, line 22 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFMZ10Db5da4ooeu8:-MdcFMZ10Db5da4ooeu9:b-9rijir) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L22)):*
> ```JavaScript
> 
>   const moveToNextItem = () => {
>     const newIndex = (index + 1) % keys.length;
> ```

I would name it `nextItemIndex`
___
*[src/components/Carousel/Carousel/index.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFct30LcEUamWrl7K:-MdcFct30LcEUamWrl7L:bb7od0r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L27)):*
> ```JavaScript
> 
>   const moveToPreviousItem = () => {
>     let newIndex = (index - 1) % keys.length;
> ```

same
___
*[src/components/Carousel/Carousel/index.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFe121Tld2UP3ZtGG:-MdcFe121Tld2UP3ZtGH:b8iufmk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L28)):*
> ```JavaScript
>   const moveToPreviousItem = () => {
>     let newIndex = (index - 1) % keys.length;
>     if ( newIndex < 0 ) newIndex = keys.length - 1
> ```

use clauses {}
___
*[src/components/Carousel/Carousel/index.js, line 34 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFky67stn5R8iobmk:-MdcFky67stn5R8iobml:b3da32i) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L34)):*
> ```JavaScript
> 
>   
>   const _slides = () => {
> ```

don't use the underscore convention, it used to mark variables/methods as private, I don't like it since its not really private :)
___
*[src/components/Carousel/Carousel/index.js, line 42 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcIMWn7BUem0C7-iBu:-MdcIMWn7BUem0C7-iBv:bb7od0r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L42)):*
> ```JavaScript
>   }
> 
>   const _sliderDots = () => {
> ```

same
___
*[src/components/Carousel/Carousel/index.js, line 45 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcIOG77e8q80GusLgE:-MdcIOG77e8q80GusLgF:bubzhxl) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L45)):*
> ```JavaScript
>     return keys.map(key => (
>       <span key={key} onClick={() => setIndex(key)}>
>         {<DotIcon selected={key === index} />}
> ```

you don't need the parentheses 
___
*[src/components/Carousel/Carousel/index.js, line 54 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJ5168F_ttd21-MO4:-MdcIa2v4Gv20SAygH24:b-bhml07) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L54)):*
> ```JavaScript
>       <div className="grid grid-flow-row auto-rows-max">
>         <div className='flex flex-row justify-center'>
>         <button className='focus:outline-none' onClick={moveToNextItem}>          <svg className="h-10 w-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
> ```

seems like a little mess here
actually it will be nice if you will move all the svg code to a dedicated svg file.
___
*[src/components/Carousel/Carousel/index.js, line 60 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJ68i1v27CNYknMk9:-MdcIl1W1_gyva7qMRdh:bb7od0r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L60)):*
> ```JavaScript
>           { _slides() }
>         </div>
>         <button onClick={moveToPreviousItem} className='focus:outline-none'>          <svg className="h-10 w-10" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
> ```

same
___
*[src/components/Carousel/Slides/index.js, line 2 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJg7TBkFsvTgGbMR4:-MdcJg7TBkFsvTgGbMR5:b-stbye2) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Slides/index.js#L2)):*
> ```JavaScript
> import React from 'react';
> import { IMAGES } from '../../mock';
> ```

what is mock? do you use this file?
___
*[src/components/Pages/Home/Home.jsx, line 79 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJyP888LD3bQaOBH4:-MdcJyP888LD3bQaOBH5:b-ou2sev) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Pages/Home/Home.jsx#L79)):*
> ```JavaScript
>           <div className=" ">
>             <Carousel time={8000}>
>               {usOnMediaArticles.map(({ title, img, link_to_article }) => (
> ```

no snake_case

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16)* status: all files reviewed, 15 unresolved discussions (waiting on @nir2002)

___
*[package.json, line 76 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-Mdc7Zpc-WQ3K7qSjZkb:-MdkhIxX-DMl41U0nhQD:buwnx6g) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/package.json#L76)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you're using two different packages?
</blockquote></details>

no' just missed that uninstallation. uninstalled it
___
*[src/components/Carousel/Carousel/index.js, line 1 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEJZ15j3PFeeUrNih:-Mdkn_SM6SqZT1l6rIoM:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L1)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. Why do you have two nested folders named Carousel ?
2. rename the file to Carousel and use the index.js pattern
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 10 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEYyj22nbwvP-fZih:-MdknxKb2GSwtmu949jF:b-7m74ox) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L10)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you can refactor it to:
```
const interval = setInterval(moveToNextItem, time)
```
</blockquote></details>

nice!
___
*[src/components/Carousel/Carousel/index.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEhDK0w0FD_u8V5y2:-MdktNfI-MUgP7tdzyr5:bdvtuqh) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L13)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I don't think `interval` is defined when this function is called, test it.
</blockquote></details>

I don't see this cleanup function is being called, but this is how I saw they to it in the internet. delete it or leave it?
___
*[src/components/Carousel/Carousel/index.js, line 17 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcEsMlAWeCnhTUx6kr:-MdkqGlI3gAMyv7oPJym:b3n4dgs) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L17)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. why?
2. use clause {}
3. save 1000 is informative constant
</blockquote></details>

1. if time == 0 then carousel starts flickering, so set minimum time
2. done
3. done
___
*[src/components/Carousel/Carousel/index.js, line 22 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFMZ10Db5da4ooeu8:-MdkqqUrDJ4cRgHN0CSp:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L22)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I would name it `nextItemIndex`
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFct30LcEUamWrl7K:-Mdkqqvp5lHTnbrQxR1z:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L27)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFe121Tld2UP3ZtGG:-Mdkqv9t5fjmEpDmzcVw:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L28)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

use clauses {}
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 34 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcFky67stn5R8iobmk:-Mdkr1tk8BbzdBYnLEHu:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L34)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

don't use the underscore convention, it used to mark variables/methods as private, I don't like it since its not really private :)
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 42 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcIMWn7BUem0C7-iBu:-Mdkr2Pu7bhbSk6q_tPF:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L42)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/components/Carousel/Carousel/index.js, line 45 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcIOG77e8q80GusLgE:-MdkrBEVEMYjBSkBJle5:b-hfpv0l) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L45)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you don't need the parentheses 
</blockquote></details>

removed
___
*[src/components/Carousel/Carousel/index.js, line 54 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJ5168F_ttd21-MO4:-MdkxBdS1oKtl3-QOFO6:b-1zh2vq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L54)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

seems like a little mess here
actually it will be nice if you will move all the svg code to a dedicated svg file.
</blockquote></details>

Done.
(and prettier wasn't working temporary and I missed that)
___
*[src/components/Carousel/Carousel/index.js, line 60 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJ68i1v27CNYknMk9:-MdkxBzjC7nctuPuczGM:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Carousel/index.js#L60)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/components/Carousel/Slides/index.js, line 2 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJg7TBkFsvTgGbMR4:-MdkrXvyBB_vnlJZ1hMg:b-q9pwyf) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Carousel/Slides/index.js#L2)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what is mock? do you use this file?
</blockquote></details>

this whole file is a leftover from the original code. deleted it
___
*[src/components/Pages/Home/Home.jsx, line 79 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-MdcJyP888LD3bQaOBH4:-Mdks8xP4VtIaeIPMR8H:b-rh22ye) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0f4c83cb11bba67406ae37b5f8d9f7b4adb60d88/src/components/Pages/Home/Home.jsx#L79)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

no snake_case
</blockquote></details>

changed to <code>link_to_article: linkToArticle</code> and used  <code>linkToArticle</code> anywhere else.
Is it good enough? <code>link_to_article</code> is defined in <code>config.yml</code> file and the names there are snake_case

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

___
*[src/components/Carousel/index.js, line 14 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-Mdl1HNU1g5xz3DTjR0k:-Mdl1HNU1g5xz3DTjR0l:bsc8sak) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6376282ae6e560705b027f5ee07a79904200da6a/src/components/Carousel/index.js#L14)):*
> ```JavaScript
>   useEffect(() => {
>     const interval = setInterval(moveToNextItem, time);
>     return () => clearInterval(interval);
> ```

the cleanup function is invoked when the component is unmounted, for example when you change the page, try to print something and see if it happens
try also to print interval and see if it exists, it might exists because of closure.

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16)* status: all files reviewed, 1 unresolved discussion (waiting on @nir2002)

___
*[src/components/Carousel/index.js, line 14 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/16#-Mdl1HNU1g5xz3DTjR0k:-Mdl4Cu72kpbkH5zoRI0:b2uqoid) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6376282ae6e560705b027f5ee07a79904200da6a/src/components/Carousel/index.js#L14)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

the cleanup function is invoked when the component is unmounted, for example when you change the page, try to print something and see if it happens
try also to print interval and see if it exists, it might exists because of closure.
</blockquote></details>

did just that. nothing was printed. changed to another page to unmount the component and nothing was printed.
tried again, still nothing is printed...

**Pull request merged**
