### PR TITLE
deature/democ-education

### PR DESCRIPTION
**Pull request by IdanSchiller**
This change is [Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)

### CODE REVIEW

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 5 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[tailwind.config.js, line 29 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadqP8c39q-bfVHM0uf:-MadqP8c39q-bfVHM0ug:b-31m6v1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/2927ced83fae1a1c3ac44e87ffbd9bc0f1d3acd7/tailwind.config.js#L29)):*
> ```JavaScript
>       },
>       boxShadow: {
>         DemocEducImg : '0 0 14px -3px rgba(0,0,0,.67)'
> ```

1. Are these values fit all screen sizes?
2. Keep it lower case (`demoEducImg`)
___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 52 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadS7xb5A3e4lgKw-Vm:-MadtEJJBxdbLxbBrLEV:b-lt4bno) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L52)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

1. I'm not sure I understand. which title? I can't see anything wrong. 
the page main (not the header) should not be centered on mobile (as far as I can see).
I have added a left margin to the text though (deleted the md: breakpoint in the div below)
2. you're right, I don't, mistake.
</blockquote></details>



see that the title is pushed to the right?

Also, something is broken since your last commit, all the right space has been deleted

___
*[src/styles/mdxStyles.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUwY980J08iKh_AQw:-MadrFAb1WHbo4__fSGS:busyuk9) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L4)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

move the component down?
if I do that then the styling do not apply.
does that happen because of the linter?
</blockquote></details>

Yes, below the `mdStyle`
It should work, eslint is only for enforcing development rules, it can fail the build process but I saw it lets it pass in this case, strange.

Give it 5 minutes and if you can't fix it then leave it like this, I just don't see any reason the customized components or help function should be on top of the file -  I think that at the top of the file should be the most important and interesting part of the file and below it all the utilities.
___
*[src/styles/mdxStyles.js, line 33 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUpK2EmTE8LU8jI7X:-MadqsD91MyCXh1a5njY:bvzmokd) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L33)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Done.
But why?
</blockquote></details>

Actually, I have no idea =) the code review tools (Github) yelling at this and I don't like to be yelled at :)

**Review by nir2002 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 5 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/Page/Page.jsx, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadQZFE0zBYm0zpwbzx:-Madtp2e1Q-F2Pk7x0Tt:b7hv8of) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/components/Page/Page.jsx#L16)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

> And if we want to build a page not out of a markdown file?
then the styling in mdxStyles will not apply.
and we can override these mdx styles in page itself if we want to style the mdx differently.
make it configurable anyway? (with a flag prop?)
</blockquote></details>

What I meant is I want to leave the option to build a page without reading content from a markdown file, just use a custom component with static hard coded data

If I can do that with the existing code so great, leave it that way. If not then yes, flag prop is ok.

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 5 unresolved discussions (waiting on @nir2002)

___
*[tailwind.config.js, line 29 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadqP8c39q-bfVHM0uf:-Mae8LEj4xkvKGmdcS_R:bjacc5v) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/2927ced83fae1a1c3ac44e87ffbd9bc0f1d3acd7/tailwind.config.js#L29)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. Are these values fit all screen sizes?
2. Keep it lower case (`demoEducImg`)
</blockquote></details>

1. it seems so, and in the original site these values also stays the same for all screen sizes.
2. changed it.
___
*[src/components/Page/Page.jsx, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadQZFE0zBYm0zpwbzx:-Mae3VnQ4B1_qv2NZPtG:b-le847i) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/components/Page/Page.jsx#L16)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

What I meant is I want to leave the option to build a page without reading content from a markdown file, just use a custom component with static hard coded data

If I can do that with the existing code so great, leave it that way. If not then yes, flag prop is ok.
</blockquote></details>

as far as I tested it, the mdx styling does not apply on regular html elements
___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 52 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadS7xb5A3e4lgKw-Vm:-Mae41rMCROfnbZI7v5T:b37uuj0) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L52)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>



see that the title is pushed to the right?

Also, something is broken since your last commit, all the right space has been deleted


</blockquote></details>

OK I see that now, on quite narrow screens.
<code>text-center<code> in the header fixed that (for the record, I didn't touch the Page.Header component at all)

I fixed the break, it's centered now.
___
*[src/styles/mdxStyles.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUwY980J08iKh_AQw:-Mae5tkwB60lwrtApDyy:b-p0l2t8) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L4)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Yes, below the `mdStyle`
It should work, eslint is only for enforcing development rules, it can fail the build process but I saw it lets it pass in this case, strange.

Give it 5 minutes and if you can't fix it then leave it like this, I just don't see any reason the customized components or help function should be on top of the file -  I think that at the top of the file should be the most important and interesting part of the file and below it all the utilities.
</blockquote></details>

I also think help function ect. should be at the bottom, but it just didn't work.
maybe because the mdStyle object is constructed before the Blockquote component is or something...
If you move it down and add a blockquote ('>') in the .md file it applies the custom styling (or a styling at all) ? for me it didn't.
Plus I haven't worked with a linter before and the <code>eslint</code> files in the project doesn't tell me much...
___
*[src/styles/mdxStyles.js, line 33 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUpK2EmTE8LU8jI7X:-Mae2vk2EhregwVxYrgj:b-s29qj5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L33)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Actually, I have no idea =) the code review tools (Github) yelling at this and I don't like to be yelled at :)
</blockquote></details>

strange, yell back at him

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 3 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/Page/Page.jsx, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadQZFE0zBYm0zpwbzx:-Mah0vgmA-Z10f_HamIT:b-22j8lt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/components/Page/Page.jsx#L16)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

as far as I tested it, the mdx styling does not apply on regular html elements
</blockquote></details>

ok great then
___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 48 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0h0w3ayUPN_6lME2:-Mah0h0w3ayUPN_6lME3:bd8q7ib) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L48)):*
> ```JavaScript
>       </Page.Header>
>       <Page.Main>
>         <div className="md:flex flex-row m-auto md:w-4/5">
> ```

why did you return it?
___
*[src/components/Pages/Gan/Gan.jsx, line 19 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0crD36g35f33o4Lm:-Mah0crD36g35f33o4Ln:b3kre) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/Gan/Gan.jsx#L19)):*
> ```JavaScript
>         <div>
>           תוכן העמוד
>           <h2 className="text-xl">ffddfddf</h2>
> ```

?
___
*[src/styles/mdxStyles.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUwY980J08iKh_AQw:-Mah0FPC2fY2TgI1ojRK:b-462uy0) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L4)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

I also think help function ect. should be at the bottom, but it just didn't work.
maybe because the mdStyle object is constructed before the Blockquote component is or something...
If you move it down and add a blockquote ('>') in the .md file it applies the custom styling (or a styling at all) ? for me it didn't.
Plus I haven't worked with a linter before and the <code>eslint</code> files in the project doesn't tell me much...
</blockquote></details>

ok let leave it like this and talk about it and about eslint next time we meet
___
*[src/styles/mdxStyles.js, line 32 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0R4I6RgAOJ2-O9e5:-Mah0R4I6RgAOJ2-O9e6:b-pubb0h) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/styles/mdxStyles.js#L32)):*
> ```JavaScript
>     
>     export {mdStyle};  
>       
> ```

see the red things here? if you go to GitHub it will yell at you :)
so empty new line please

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 3 unresolved discussions (waiting on @nir2002)

___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 48 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0h0w3ayUPN_6lME2:-Mai0q6l6E_OdVkk8qGr:b-torytb) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L48)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why did you return it?
</blockquote></details>

I've removed the <code>justify-center</code>, apparently it doesn't apply when I set the width. I could use <code>justify-center</code> + <code>mx-20</code>, but <code>m-auto</code> seems to work better
___
*[src/components/Pages/Gan/Gan.jsx, line 19 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0crD36g35f33o4Lm:-Mahy6vw8OHwwy4QqWIF:b6xfezo) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/Gan/Gan.jsx#L19)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

?
</blockquote></details>

shit I knew I forgot to delete something. deleted.
___
*[src/styles/mdxStyles.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-MadUwY980J08iKh_AQw:-MahyEJX1XEJvt4auihZ:b32w0x) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/577a8e86cc1ef40be1361553f970cd175f06c983/src/styles/mdxStyles.js#L4)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

ok let leave it like this and talk about it and about eslint next time we meet
</blockquote></details>

OK
___
*[src/styles/mdxStyles.js, line 32 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0R4I6RgAOJ2-O9e5:-MahysWn1pPrtMqrdr2G:bu2wowi) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/styles/mdxStyles.js#L32)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

see the red things here? if you go to GitHub it will yell at you :)
so empty new line please
</blockquote></details>

OK I though I it was empty but apparently there were 3 tabs in that line. fixed.

**Review by nir2002 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 48 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0h0w3ayUPN_6lME2:-MalZjy2-bGFxlts79Eo:b-pthrdw) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L48)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

I've removed the <code>justify-center</code>, apparently it doesn't apply when I set the width. I could use <code>justify-center</code> + <code>mx-20</code>, but <code>m-auto</code> seems to work better
</blockquote></details>

put the flex and justify center style on the main component, then it will work.

**Review by IdanSchiller — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: all files reviewed, 1 unresolved discussion (waiting on @nir2002)

___
*[src/components/Pages/DemocraticEducation/DemocraticEducation.jsx, line 48 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3#-Mah0h0w3ayUPN_6lME2:-Manjdb5ALI-myJeNNgk:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/ab11e214fc8b32e04f399c1f476a66bb754486fe/src/components/Pages/DemocraticEducation/DemocraticEducation.jsx#L48)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

put the flex and justify center style on the main component, then it will work.
</blockquote></details>

Done.

**Review by nir2002 — APPROVED** [review]
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)

**Pull request merged**
