### PR TITLE
feature/signup-page

### PR DESCRIPTION
**Pull request by nir2002**
This change is [Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)

### CODE REVIEW

**Review by IdanSchiller — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)* status: all files reviewed, 4 unresolved discussions (waiting on @nir2002)

___
*[src/components/Inputs/Inputs.jsx, line 90 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-MczAZ40D6yssI8DX6Wu:-MczAZ40D6yssI8DX6Wv:bla11b5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Inputs/Inputs.jsx#L90)):*
> ```JavaScript
> }
> 
> export function TextBox({ label, onChange, fieldName }) {
> ```

maybe add 'required' prop if you like
___
*[src/components/Pages/Contact/ContactForm.jsx, line 12 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz6JzM8ts9NXHsqbJt:-Mcz6JzM8ts9NXHsqbJu:b-tnn5ow) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Contact/ContactForm.jsx#L12)):*
> ```JavaScript
> 
> function getAgeInSep(date) {
>   const diff = new Date('09/01/2021') - new Date(date);
> ```

what about next year? maybe year (2021) should be the current year from <code>Date</code>
___
*[src/components/Pages/Signup/Signup.jsx, line 31 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz7nyA4nofk0eG7gPa:-Mcz7nyA4nofk0eG7gPb:bthwa90) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Signup/Signup.jsx#L31)):*
> ```JavaScript
>   return (
>     <Page>
>       <Page.Header>
> ```

<code> < SEO > </code>  can be inserted under this line
___
*[src/components/Pages/Signup/SignupForm.jsx, line 13 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz89Q73Gs7Q-U7iYoa:-Mcz89Q73Gs7Q-U7iYob:b54rvzd) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Signup/SignupForm.jsx#L13)):*
> ```JavaScript
> }
> 
> function getAgeInSep(date) {
> ```

Duplicated from <code> ContactForm.jsx </code>, you can put it in utils.js if you like

**Review by nir2002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)* status: all files reviewed, 4 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/Inputs/Inputs.jsx, line 90 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-MczAZ40D6yssI8DX6Wu:-MdMWvsw76M_lqsjvPJZ:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Inputs/Inputs.jsx#L90)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

maybe add 'required' prop if you like
</blockquote></details>

Done.
___
*[src/components/Pages/Contact/ContactForm.jsx, line 12 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz6JzM8ts9NXHsqbJt:-MdMWygj5DWaCSGldPuT:bt0i6na) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Contact/ContactForm.jsx#L12)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

what about next year? maybe year (2021) should be the current year from <code>Date</code>
</blockquote></details>

You're right 😅
Add some new logic, please go over it and tell me if it makes sense
actually, this should be set through the CMS, what do you think will be the best to do this?
___
*[src/components/Pages/Signup/Signup.jsx, line 31 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz7nyA4nofk0eG7gPa:-MdMcFHI7U_8Vw0HMRVt:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Signup/Signup.jsx#L31)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

<code> < SEO > </code>  can be inserted under this line
</blockquote></details>

Done.
___
*[src/components/Pages/Signup/SignupForm.jsx, line 13 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz89Q73Gs7Q-U7iYoa:-MdMcIAs3CokYJdGcXrw:b-uq3q61) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Signup/SignupForm.jsx#L13)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Duplicated from <code> ContactForm.jsx </code>, you can put it in utils.js if you like
</blockquote></details>

it will be removed from ContactForm, and its not really a utility, only used here
but great comment, thanks!

**Review by IdanSchiller — APPROVED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @IdanSchiller and @nir2002)

___
*[src/components/Pages/Contact/ContactForm.jsx, line 12 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz6JzM8ts9NXHsqbJt:-MdbBvz7AtxkoI_H3ygU:b-sq35ze) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Contact/ContactForm.jsx#L12)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

You're right 😅
Add some new logic, please go over it and tell me if it makes sense
actually, this should be set through the CMS, what do you think will be the best to do this?
</blockquote></details>

looks good.
maybe an .md file with all the configurations will be suitable?

**Review by IdanSchiller — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)* status: all files reviewed, 1 unresolved discussion (waiting on @nir2002)

**Review by nir2002 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

___
*[src/components/Pages/Contact/ContactForm.jsx, line 12 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/13#-Mcz6JzM8ts9NXHsqbJt:-MdpC6F97cctxDsC8x2b:b-ed3qgt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/c4d0c6632d7c7d51462383f03d25aae3835d83f6/src/components/Pages/Contact/ContactForm.jsx#L12)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

looks good.
maybe an .md file with all the configurations will be suitable?
</blockquote></details>

I'll create a different task for this

**Pull request merged**
